import timestamp from 'lib/utils/timestamp';

import frame from './frame';
import { fontList } from '../styleProps';

import css from 'lib/generator/css/index';
import js from 'lib/generator/js/index';
import widthRange from 'lib/generator/widthRange';

export default ({ config, assets, variables }) => {
	let containerId = `${config.syntax}-box`;

	let html = `<!-- Generated by figma2html on ${timestamp()} -->`;

	let frameCss = assets
		.map(({ node, filename }) =>
			frame({
				node,
				filename,
				widthRange: widthRange(assets),
				altText: config.altText,
				config,
				variables,
			}).css
		)
		.join('\n\n');

	html += `\n\n<style>\n${css.page({
		containerId,
		config,
		frameCss
	})}\n</style>`;

	html += `\n\n<div id="${containerId}" class="figma2html">`;

	if (config.clickableLink)
		html += `\n\t<a class="f2h-link" href="${config.clickableLink}">`;

	html += `\n${config.clickableLink ? '\t\t' : '\t'}${assets
		.map(({ node, filename }) =>
			frame({
				node,
				filename,
				widthRange: widthRange(assets),
				altText: config.altText,
				config,
				variables,
			}).html
		)
		.join('\n\n')}`;

	if (config.clickableLink) html += `\n\t</a>`;

	if (config.includeResizer) html += `\n\n${js.resizer(containerId, false)}`;

	if (config.includeGoogleFonts && !!fontList.length)
		html += `\n\n${js.fonts(fontList)}`;

	html += `\n\n<!-- End figma2html generated content - ${timestamp()} -->`;

	return html;
};
